[project]
name = "bigquery-notebook"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ipython>=9.7.0",
    "jupyter>=1.1.1",
    "pip>=25.3",
    "python-dotenv>=1.2.1",
]
